## Numpy Assignment
Student Name: AINEMBABAZI MOSES

Reg No: 2022/HD07/2039U

## Instructions:
- Please complete the questions below.
- Please comment your code indicating how you approached the problem

# What is NumPy, and what are some of its key features?
The numerical python (numpy) is a python llibrary used to work with numerical data in python ans is at the core of scientific python and pyData ecostems.

The NumPy API is used extensively in Pandas, SciPy, Matplotlib, scikit-learn, scikit-image and most other data science and scientific Python packages.

NumPy can be used to perform a wide variety of mathematical operations on arrays. It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.

some of the Key features include
-N-dimensional arrays: NumPy provides a powerful N-dimensional array object that can be used to store and manipulate data efficiently.

-Broadcasting: Broadcasting is a powerful feature in NumPy that allows arrays with different shapes to be used in arithmetic operations. This can save time and memory by avoiding the need to create explicit copies of arrays.

-Vectorized operations: NumPy allows you to perform operations on entire arrays at once, which is much faster than performing the same operations on individual elements in a loop.

-Mathematical functions: NumPy provides a wide range of mathematical functions, including trigonometric functions, exponential functions, and logarithmic functions, to name just a few.

-Linear algebra: NumPy provides a suite of linear algebra functions, including matrix multiplication, matrix inversion, and eigenvalue decomposition.

In [24]:
# to install numpy when you have python installed.

#conda install numpy or 

#pip install numpy

# How do you create a NumPy array using Python's built-in range() function?

in oder to create this array i will have to use numpy.array() or numpy.arange methods and pass the out put of range() function as an arguement.

In [8]:
#numPy array using built in  range() funcction.
# first import numpy

import numpy as np

arr1 = np.array(range(8))
print(arr1)

# you can also create a numpy array using arange method
arr2 = np.arange(10)
print(arr2)

[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7 8 9]


# What is the difference between a scalar value and a vector in NumPy?

a scalar value in numpy is a single value or a number, whereas a vector is an array of values.
A scalar value in NumPy has zero dimensions and can be created using the numpy.array() method with a single argument while the array has more than one dimensions.

In [26]:
# create a scalar value, it has no range
mozey = np.array(12) #scalar value of 12 using the numpy.array() method with a single argument.
print(mozey)

12


In [27]:
#a vector in NumPy has one or more dimensions and can be created using the numpy.array() method 
# with a sequence of values or a list.

# create a vector with one dimension
vec1 = np.array([0, 2, 3, 6, 5])
print(vec1)



[0 2 3 6 5]


In [28]:
# create a vector with two dimensions
vec2 = np.array([[1, 4, 3], [7, 5, 8]])
print(vec2)

[[1 4 3]
 [7 5 8]]


# How do you calculate the mean of a NumPy array using the mean() function?

Python NumPy array mean() function is used to compute the arithmetic mean or average of the array 
elements along with the specified axis or multiple axis. You get the mean by calculating the sum of 
all values in a Numpy array divided by the total number of values.



In [29]:
# lets get the mean nof  a two dimensional array
array2d = np.array([[6, 3, 9, 8], [5, 3, 2, 7]])

 # mean function to find mean of the array
np = np.mean(array2d)

print(np)

5.375


# What is broadcasting in NumPy, and how can it be useful?
-NumPy broadcast() function in Python is used to return an object that mimics broadcasting. 
-It describes the ability of NumPy to treat arrays of different shapes during arithmetic operations. 
The broadcasting rules of NumPy are designed to be intuitive and to work naturally with the way mathematical operations are performed. The rules can be summarized as follows:

If the arrays have the same shape, then the operation is performed element-wise on the corresponding elements.

If the arrays have different shapes, then the array with fewer dimensions is padded with ones on its leading (left) side until the shapes have the same length.

If the arrays have the same number of dimensions, but their shapes do not match, then the array with shape equal to 1 in a given dimension is stretched to match the shape of the other array in that dimension.

In [48]:
# shape is (3,)
ab = np.array([3, 2, 3])  

# shape is (3,1)   
bc = np.array([[4], [6], [8]]) 

# add the arrays using broadcasting
ct = ab + bc

print(ct)


[[ 7  6  7]
 [ 9  8  9]
 [11 10 11]]


# How can you slice a NumPy array to extract a subarray?

Slicing in NumPy is the operation of extracting a portion of a NumPy array based on a specified range of indices. It allows you to create a view of a portion of the array without copying the data.

Slicing in NumPy is similar to slicing in Python's built-in lists, but with some additional features. You can use slicing to extract a subarray, or a specific portion of an array along one or more dimensions. Slicing in NumPy is accomplished using the slicing notation, which uses the colon : to specify a range of indices.



In [70]:
#How can you slice a NumPy array to extract a subarray?

# create a 2D array
slicearr = np.array([[1, 10, 3], [7,12, 6], [7, 8, 9]])

# extract a subarray specifying start rows and end columns
subset_arr= slicearr[0:2, 0:2]

# print the subarray
print(subset_arr)


[[ 1 10]
 [ 7 12]]


# What are some of the available functions for performing element-wise operations on NumPy arrays?
Element-wise operations in NumPy refer to mathematical operations that are performed on each element of a NumPy array individually, rather than on the array as a whole. In other words, the operation is applied to each element of the array separately and independently of the other elements.

    -np.add(): Adds corresponding elements in two arrays.

    -np.subtract(): Subtracts corresponding elements in two arrays.

    -np.multiply(): Multiplies corresponding elements in two arrays.

    -np.divide(): Divides corresponding elements in two arrays.

    -np.ceil(): Rounds each element in the array up to the nearest integer.

    -np.power(): Computes the power of each element in the array.

    -np.maximum(): Computes the maximum of corresponding elements in two arrays.

    -np.minimum(): Computes the minimum of corresponding elements in two arrays
    
    -np.round(): Rounds each element in the array to the nearest integer.

In [77]:
#example of element wise operations

vb = np.array([2,3,4,5,6])

#lets use * for multiplication and will be applied to each element

a = 2 * vb

# or we can add 3 to ech element in the array
b = 3 + vb

print(a)

print(b)

[ 4  6  8 10 12]
[5 6 7 8 9]


# How do you reshape a NumPy array to have a different shape?
Reshaping a NumPy array to have a different shape, you can use the reshape() function.
The reshape() function returns a new NumPy array with the same data but a different shape. 
The syntax for reshape() function is:




In [82]:
mzy = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

b = np.reshape(mzy, (2, 3, 2))

print(b)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# How do you perform matrix multiplication on two NumPy arrays using the dot() function?
For matrix multiplication to be valid, the number of columns of the first matrix must be equal to the number of rows of the second matrix
 both arrays have the same number of rows and columns, they are both square matrices. However, for matrix multiplication to be valid, they need to be transposed in such a way that the number of columns of the first matrix matches the number of rows of the second matrix

In [8]:
import numpy as np

#two square matrices since the number of columns and rows are the same
myarr = np.array([[7, 4, 5], [6, 9, 2]])
arr1 = np.array([[3, 5, 1], [7, 8, 9]])
#transpose one of the arrays so that it has the correct shape for matrix multiplication.
arr1 = arr1.T #use .T for transposing
array2 = np.dot(myarr, arr1)

print(array2)

[[ 46 126]
 [ 65 132]]


# How can you use the where() function to apply a condition to a NumPy array?

numpy.where() function can be used to apply a condition to a NumPy array and return the indices where the condition is true. The general syntax of the where() function
numpy.where(condition[, x, y]), x is the value to be returned where the condition is true, and y is the value to be returned where the condition is false. If x and y are not specified, 
where() returns a tuple of arrays containing the indices where the condition is true.

In [20]:


# Create a 1D NumPy array
arr_id = np.array([1, 2, 3, 4, 5])

# Apply a condition to the array
cond = arr_id > 3

# Use where() to return the indices where the condition is true
indices = np.where(cond)

print(indices)


(array([3, 4]),)


In [9]:
#use where() to replace values in an array based on a condition.
# To do this, you can pass the array itself as the second argument to where() and the replacement value as the third argument.

# Create a 1D NumPy array
arr_where = np.array([1, 2, 3, 4, 5])

# Replace values in the array based on a condition
arr_where = np.where(arr > 3, 10, arr_where)

print(arr_where)


NameError: name 'arr' is not defined

# What is the difference between the flatten() and ravel() functions in NumPy?

What is the difference between the Numpy flatten and ravel functions? The main functional distinction is that flatten is a function of an ndarray object and hence only works with genuine numpy arrays. ravel(), on the other hand, is a library-level function that may be invoked on any object that can be correctly parsed. For example, ravel() may work on a list of ndarrays, although flatten will not clearly.
numpy.ravel() Function
Syntax :

numpy.ravel(a, order='C')
NumPy’s ravel function can only accept two parameters, one of which is "a," which is used to provide the input array to the function. The second argument is ordered, which is the default parameter. A 1-D array is constructed by packing the items of "a" in the order indicated by the order parameter.

ndarray.flatten() Function
Syntax :

ndarray.flatten(order='C')
It just needs one argument, order, which is the default parameter. Similar to the ravel function order, this specifies the order in which the NumPy array will be built by packing the items of a ndarray.



In [24]:


# Create a 5x3 two-dimensional array with consecutive integers from 0 to 14
original_array = np.arange(15).reshape(5, 3)

# Use the ravel() function to flatten the original array and store the result in a new variable a
a = original_array.ravel()

# Use the flatten() function to create a copy of the original array and flatten it, storing the result in a new variable b
b = original_array.flatten()

# Modify the third element of the flattened array b to be 10000
b[2] = 1000

# Print the original array, which is not affected by modifying the copy b
print('Original array:\n', original_array)

# Print the modified array b
print("Array b : ", b)

# Modify the third element of the flattened array a to be 10000
a[2] = 1000

# Print the original array, which is now affected by modifying the reference a
print('Original array:\n', original_array)

# Print the modified array a
print("Array a : ", a)


Original array:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
Array b :  [   0    1 1000    3    4    5    6    7    8    9   10   11   12   13
   14]
Original array:
 [[   0    1 1000]
 [   3    4    5]
 [   6    7    8]
 [   9   10   11]
 [  12   13   14]]
Array a :  [   0    1 1000    3    4    5    6    7    8    9   10   11   12   13
   14]


# How do you use NumPy's advanced indexing capabilities to select specific elements from an array?
NumPy provides advanced indexing capabilities to select specific elements from an array. There are two types of advanced indexing:

Boolean indexing: Selecting elements from an array based on a Boolean condition.

Integer indexing: Selecting elements from an array based on their index or position.
 Advanced indexing is triggered when obj is : 

an ndarray of type integer or Boolean
or a tuple with at least one sequence object
is a non tuple sequence object
Advanced indexing returns a copy of data rather than a view of it. Advanced indexing is of two types integer and Boolean.

Purely integer indexing : When integers are used for indexing. Each element of first dimension is paired with the element of the second dimension. So the index of the elements in this case are (0,0),(1,0),(2,1) and the corresponding elements are selected.

In [23]:
# Python program showing advanced indexing
a = np.array([[1 ,2 ],[3 ,4 ],[5 ,6 ]])
print(a[[0 ,1 ,2 ],[0 ,0 ,1]])




[1 3 6]


In [22]:
# You may wish to select numbers greater than 50
# this is done in boolean indedxing
 
a = np.array([10,40, 400, 870, 50, 100])
print(a[a>50])

[400 870 100]


# How can you use NumPy's broadcasting rules to perform operations on arrays with different shapes?
The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.

In [21]:
#How do you perform element-wise division of two NumPy arrays while ignoring divide-by-zero errors?
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

### Project: Array Statistics Calculator
**Description:**

In this project, you will create a program that allows a user to enter a list of numbers, and then calculates and displays various statistics about those numbers using NumPy.

**Requirements:**

- The program should prompt the user to enter a list of numbers separated by commas.
- The program should use NumPy to convert the input into a 1D NumPy array.
- The program should calculate and display the following statistics:
- The mean of the numbers
- The median of the numbers
- The standard deviation of the numbers
- The maximum and minimum values of the numbers
- The program should use appropriate NumPy functions to calculate the statistics.
- The program should display the statistics with appropriate labels.

### Sample Output
```
Enter a list of numbers separated by commas: 2, 5, 7, 3, 1, 9
Statistics for the input array:
Mean: 4.5
Median: 4.0
Standard Deviation: 2.9154759474226504
Maximum: 9
Minimum: 1
```

In [71]:

# Prompt the user to enter a list of numbers separated by commas
num_list = input("Enter a list of numbers separated by commas: ")

# Convert the input into a 1D NumPy array
num_array = np.array([float(x) for x in num_list.split(',')])

# Calculate the statistics using NumPy functions
mean = np.mean(num_array)
median = np.median(num_array)
std_dev = np.std(num_array)
max_val = np.max(num_array)
min_val = np.min(num_array)

# Display the statistics with appropriate labels
print("Statistics:")
print("Mean: ", mean)
print("Median: ", median)
print("Standard Deviation: ", std_dev)
print("Maximum Value: ", max_val)
print("Minimum Value: ", min_val)


Statistics:
Mean:  6.0
Median:  6.5
Standard Deviation:  2.3804761428476167
Maximum Value:  9.0
Minimum Value:  2.0
